import './globals.css'
import type { Metadata } from 'next'

import Navbar from "@/components/Navbar";
import NextAuthProvider from "@/app/provider";
import {Toaster} from "react-hot-toast";



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <NextAuthProvider>
          <Toaster />
          <Navbar />

      {children}

      </NextAuthProvider>
      </body>
    </html>
  )
}
